export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS'
export const FAILED_FETCH_INGREDIENTS = 'FAILED_FETCH_INGREDIENTS'

export const PURCHASE_BURGER_SUCCES = 'PURCHASE_BURGER_SUCCES'
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL'
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START'

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START'
export const FETCH_ORDERS_SUCCES = 'FETCH_ORDERS_SUCCES'
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'


export const AUTH_LOGOUT = 'AUTH_LOGOUT'
