export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS'
export const FAILED_FETCH_INGREDIENTS = 'FAILED_FETCH_INGREDIENTS'